"""Pure audit logic for Stage-C V2.4 coupled constraint correction."""
from __future__ import annotations
import math,re
from stage_c_collision_radius_v2_3 import barrier_crossing_gate,classify_trace,contact_gate,deep_diff_paths,geometry_gate,mobile_fixture_edge_gate,reaction_gate,semantics_gate as sphere_semantics_gate,zero_load_gate
V_INST='PHASE0S_SOFA_STAGE_C_V2_4_INSTRUMENTATION_BLOCKED';V_SEMANTICS='PHASE0S_SOFA_STAGE_C_V2_4_COUPLED_CORRECTION_SEMANTICS_FAIL';V_ZERO='PHASE0S_SOFA_STAGE_C_V2_4_ZERO_LOAD_FAIL';V_CROSS='PHASE0S_SOFA_STAGE_C_V2_4_BARRIER_CROSSING_FAIL';V_EDGE='PHASE0S_SOFA_STAGE_C_V2_4_FIXTURE_ESCAPE_PERSISTS';V_CONTACT='PHASE0S_SOFA_STAGE_C_V2_4_CONTACT_CONSTRUCTION_FAIL';V_REACTION='PHASE0S_SOFA_STAGE_C_V2_4_REACTION_PROXY_FAIL';V_GEOMETRY='PHASE0S_SOFA_STAGE_C_V2_4_GEOMETRY_FAIL';V_PASS='PHASE0S_SOFA_STAGE_C_V2_4_STABLE_CONTACT_PASS'
def intervention_gate(base,candidate):
 d=deep_diff_paths(base,candidate);c=candidate.get('constraint_correction',{});return {'diff_paths':d,'expected_diff_paths':['constraint_correction'],'mode':c.get('mode'),'wire_optimization':c.get('wire_optimization'),'regularization_term':c.get('regularization_term'),'pass':bool(d==['constraint_correction'] and c.get('mode')=='linear_solver_constraint_correction' and c.get('wire_optimization') is False and float(c.get('regularization_term'))==0)}
def component_state_is_valid(v):return bool(re.search(r'(^|[^A-Za-z])Valid([^A-Za-z]|$)',str(v).strip()))
def response_stack_gate(s,c):
 sim=c['simulation'];num=['correction_regularization_term','lcp_mu','lcp_tolerance','intersection_contact_distance_m','intersection_alarm_distance_m','beam_default_radius_m','beam_model_contact_distance_m','fixture_model_contact_distance_m','ode_rayleigh_stiffness','ode_rayleigh_mass'];finite=all(math.isfinite(float(s[x])) for x in num);out={'finite_pass':finite,**s};out['correction_component_state_valid']=component_state_is_valid(s['correction_component_state']);out['pass']=bool(finite and s['correction_class']=='LinearSolverConstraintCorrection' and out['correction_component_state_valid'] and s['correction_mode']=='linear_solver_constraint_correction' and bool(s['correction_wire_optimization']) is False and float(s['correction_regularization_term'])==0 and s['linear_solver_class']=='BTDLinearSolver' and s['ode_solver_class']=='EulerImplicitSolver' and float(s['ode_rayleigh_stiffness'])==.05 and float(s['ode_rayleigh_mass'])==.05 and s['lcp_solver_class']=='LCPConstraintSolver' and float(s['lcp_mu'])==float(sim['friction']) and float(s['lcp_tolerance'])==1e-8 and int(s['lcp_max_it'])==1000 and bool(s['lcp_build_lcp']) is False and bool(s['lcp_compute_constraint_forces']) is True and s['collision_response_class']=='CollisionResponse' and str(s['collision_response'])=='FrictionContactConstraint' and str(s['collision_response_params'])=='mu='+str(float(sim['friction'])) and bool(s['fixture_both_side']) is True and s['fixture_triangle_indices']==[[0,1,2],[0,2,3]] and float(s['intersection_contact_distance_m'])==float(sim['contact_distance_m']) and float(s['intersection_alarm_distance_m'])==float(sim['alarm_distance_m']) and float(s['beam_default_radius_m'])==float(c['beam']['radius_m']) and float(s['beam_model_contact_distance_m'])==0 and float(s['fixture_model_contact_distance_m'])==0);return out
def semantics_gate(payload,classes,candidate,point_base):
 sphere=sphere_semantics_gate(payload,classes,candidate,point_base);stack=response_stack_gate(payload['metadata']['runtime_snapshot'],candidate);return {'sphere_triangle':sphere,'response_stack':stack,'pass':bool(sphere['pass'] and stack['pass'])}
