"""Pure Stage-C V2.3 compensated Sphere/Triangle audit logic."""
from __future__ import annotations
from collections.abc import Mapping
import numpy as np
from contact_native import contact_episode_stats_timestamps
from stage_c_contact_loss_morphology import positive_to_negative_crossings

V_INPUT="PHASE0S_SOFA_STAGE_C_V2_3_INPUT_INVALID"; V_INST="PHASE0S_SOFA_STAGE_C_V2_3_INSTRUMENTATION_BLOCKED"; V_SEMANTICS="PHASE0S_SOFA_STAGE_C_V2_3_SPHERE_SEMANTICS_FAIL"; V_ZERO="PHASE0S_SOFA_STAGE_C_V2_3_ZERO_LOAD_FAIL"; V_CROSS="PHASE0S_SOFA_STAGE_C_V2_3_BARRIER_CROSSING_FAIL"; V_EDGE="PHASE0S_SOFA_STAGE_C_V2_3_FIXTURE_ESCAPE_PERSISTS"; V_CONTACT="PHASE0S_SOFA_STAGE_C_V2_3_CONTACT_CONSTRUCTION_FAIL"; V_REACTION="PHASE0S_SOFA_STAGE_C_V2_3_REACTION_PROXY_FAIL"; V_GEOMETRY="PHASE0S_SOFA_STAGE_C_V2_3_GEOMETRY_FAIL"; V_PASS="PHASE0S_SOFA_STAGE_C_V2_3_STABLE_CONTACT_PASS"
SOFA_SOURCE={"tag":"v26.06.00","local_min_distance_cpp_blob":"156df23d1c813888ebc98ec321e26292d8abbf07","sphere_collision_model_inl_blob":"f1c9370aba829aabd6d8024a58d15f3ea7c19cf6","triangle_sphere_contact_formula":"global_contact + sphere_radius + sphere_model_contact + triangle_model_contact","triangle_sphere_alarm_formula":"global_alarm + sphere_radius + sphere_model_contact + triangle_model_contact","detection_value_formula":"euclidean_native_point_distance - effective_contact_distance"}
def deep_diff_paths(a,b,prefix=""):
 if isinstance(a,Mapping) and isinstance(b,Mapping):
  return [p for k in sorted(set(a)|set(b)) for p in ([f"{prefix}.{k}" if prefix else str(k)] if k not in a or k not in b else deep_diff_paths(a[k],b[k],f"{prefix}.{k}" if prefix else str(k)))]
 if isinstance(a,list) and isinstance(b,list): return [prefix] if len(a)!=len(b) else [p for i,(x,y) in enumerate(zip(a,b)) for p in deep_diff_paths(x,y,f"{prefix}[{i}]")]
 return [] if a==b else [prefix]
def compensated_intervention_gate(base,candidate):
 d=deep_diff_paths(base,candidate); r=float(candidate["beam"]["radius_m"]);oc=float(base["simulation"]["contact_distance_m"]);oa=float(base["simulation"]["alarm_distance_m"]);nc=float(candidate["simulation"]["contact_distance_m"]);na=float(candidate["simulation"]["alarm_distance_m"])
 return {"diff_paths":d,"expected_diff_paths":["simulation.alarm_distance_m","simulation.contact_distance_m"],"beam_radius_m":r,"old_global_contact_distance_m":oc,"new_global_contact_distance_m":nc,"old_global_alarm_distance_m":oa,"new_global_alarm_distance_m":na,"old_effective_contact_distance_m":oc,"new_effective_contact_distance_m":nc+r,"old_effective_alarm_distance_m":oa,"new_effective_alarm_distance_m":na+r,"pass":d==["simulation.alarm_distance_m","simulation.contact_distance_m"] and r==.002 and (oc,nc,oa,na)==(.002,0.,.01,.008) and nc+r==oc and na+r==oa}
def effective_sphere_distances(*,sphere_radius_m,global_contact_distance_m,global_alarm_distance_m,sphere_model_contact_distance_m,triangle_model_contact_distance_m):
 common=float(sphere_radius_m)+float(sphere_model_contact_distance_m)+float(triangle_model_contact_distance_m);return {"effective_contact_distance_m":float(global_contact_distance_m)+common,"effective_alarm_distance_m":float(global_alarm_distance_m)+common}
def _value(contact,effective):return float(np.linalg.norm(np.asarray(contact["beam_contact_point_m"],float)-np.asarray(contact["fixture_contact_point_m"],float)))-float(effective)
def classify_record(record,*,effective_contact_distance_m,reaction_floor):
 contacts=record["native_contacts"]
 if int(record["native_contact_count"])!=len(contacts):raise ValueError("native_contact_count/native_contacts mismatch")
 raw=[float(c["detection_value_m"]) for c in contacts];recon=[_value(c,effective_contact_distance_m) for c in contacts]
 if not np.isfinite(raw).all():raise ValueError("non-finite raw DetectionOutput.value")
 count=sum(v<=0 for v in raw);native=bool(contacts);reaction=float(record["reaction_force_proxy"])>float(reaction_floor)
 return {"native_detection":native,"native_detection_count":len(contacts),"raw_detection_values_m":raw,"reconstructed_detection_values_m":recon,"detection_value_residuals_m":[x-y for x,y in zip(recon,raw)],"geometric_contact":bool(count),"geometric_contact_count":count,"proximity_only":native and not bool(count),"lcp_rows_present":int(record["constraint_vector_size"])>0,"reaction_active":reaction,"load_bearing_contact":bool(count) and reaction}
def classify_trace(records,**kw):return [classify_record(r,**kw) for r in records]
def first_true_index(classes,key):return next((i for i,c in enumerate(classes) if bool(c[key])),None)
def fixed(config):return {int(config["tail_constraint"]["node_index"])} if list(map(int,config["tail_constraint"]["fixed_directions"][:3]))==[1,1,1] else set()
def mobile_node_ids(config):return sorted(set(range(int(config["beam"]["nodes"]))) - fixed(config))
def _inside(p,wall,t):return float(wall["x_min_m"])-t<=p[0]<=float(wall["x_max_m"])+t and -float(wall["z_half_extent_m"])-t<=p[2]<=float(wall["z_half_extent_m"])+t
def mobile_fixture_node_ids(record,*,config):
 p=np.asarray(record["beam_node_positions_m"],float);return [n for n in mobile_node_ids(config) if _inside(p[n],config["contact_wall"],float(config["gates"]["maximum_fixture_plane_error_m"]))]
def mobile_native_detection_ids(record,*,config):return sorted({int(c["beam_element_id"]) for c in record["native_contacts"] if int(c["beam_element_id"]) in set(mobile_node_ids(config))})
def barrier_crossing_gate(records,classes,config):
 onset=first_true_index(classes,"geometric_contact")
 if onset is None:return {"evaluated":False,"reason":"no formal geometric onset","crossing_events":[],"crossing_event_count":0,"pass":True}
 events=positive_to_negative_crossings(records,wall=config["contact_wall"],plane_tol_m=float(config["gates"]["maximum_fixture_plane_error_m"]),start_index=0);events=[e for e in events if int(e["node_id"]) in set(mobile_node_ids(config)) and int(e["to_record_index"])>=onset]
 return {"evaluated":True,"formal_geometric_onset_index":onset,"formal_geometric_onset_time_s":float(records[onset]["step_end_time_s"]),"scan_start_index":0,"excluded_translation_fixed_node_ids":sorted(fixed(config)),"mobile_node_ids":mobile_node_ids(config),"crossing_events":events,"crossing_event_count":len(events),"pass":not events}
def mobile_fixture_edge_gate(records,classes,config):
 onset=first_true_index(classes,"geometric_contact");mobile=mobile_node_ids(config)
 if onset is None:return {"evaluated":False,"mobile_node_ids":mobile,"excluded_translation_fixed_node_ids":sorted(fixed(config)),"fixture_edge_escape":False,"pass":True}
 ever=any(mobile_fixture_node_ids(r,config=config) for r in records[onset:]);foot=mobile_fixture_node_ids(records[-1],config=config);native=mobile_native_detection_ids(records[-1],config=config);escape=bool(ever and not foot and not native)
 return {"evaluated":True,"formal_geometric_onset_index":onset,"formal_geometric_onset_time_s":float(records[onset]["step_end_time_s"]),"mobile_node_ids":mobile,"excluded_translation_fixed_node_ids":sorted(fixed(config)),"ever_mobile_footprint_after_onset":bool(ever),"terminal_mobile_footprint_node_ids":foot,"terminal_mobile_native_detection_ids":native,"fixture_edge_escape":escape,"pass":not escape}
def contact_gate(records,classes,config):
 pairs=[(r,c) for r,c in zip(records,classes) if r["measurement_active"]];stats=contact_episode_stats_timestamps([r["step_end_time_s"] for r,_ in pairs],[c["geometric_contact"] for _,c in pairs]);dwell=float(config["gates"]["minimum_observed_contact_dwell_ms"])/1000.;tol=float(config["integrity"]["time_tolerance_s"]);return {"measurement_samples":len(pairs),"episode":stats,"longest_episode":max(stats["episode_records"],key=lambda x:x["duration_s"],default=None),"required_occupancy":float(config["gates"]["minimum_measurement_contact_occupancy"]),"required_dwell_s":dwell,"duration_semantics":"timestamp_span_end_minus_start","time_tolerance_s":tol,"pass":stats["occupancy"]>=float(config["gates"]["minimum_measurement_contact_occupancy"]) and stats["longest_duration_s"]+tol>=dwell}
def zero_load_gate(records,classes):
 p=[c for r,c in zip(records,classes) if r["zero_load_phase"]];out={"samples":len(p),"native_detection_frames":sum(c["native_detection"] for c in p),"proximity_only_frames":sum(c["proximity_only"] for c in p),"geometric_contact_frames":sum(c["geometric_contact"] for c in p),"reaction_active_frames":sum(c["reaction_active"] for c in p)};out["pass"]=out["geometric_contact_frames"]==0 and out["reaction_active_frames"]==0;return out
def semantics_gate(payload,classes,candidate,base):
 s=payload["metadata"]["collision_snapshot"];r=float(candidate["beam"]["radius_m"]);radii=np.asarray(s["beam_list_radius_m"],float);tol=float(candidate["gates"]["maximum_fixture_plane_error_m"]);actual=effective_sphere_distances(sphere_radius_m=r,global_contact_distance_m=s["intersection_contact_distance_m"],global_alarm_distance_m=s["intersection_alarm_distance_m"],sphere_model_contact_distance_m=s["beam_model_contact_distance_m"],triangle_model_contact_distance_m=s["fixture_model_contact_distance_m"]);res=np.asarray([v for c in classes for v in c["detection_value_residuals_m"]],float);count=int(res.size);maximum=float(np.max(abs(res))) if count else 0.;out={"official_sofa_source":SOFA_SOURCE,"collision_snapshot":s,"requested_beam_radius_m":r,"radius_count":int(radii.size),"expected_radius_count":int(candidate["beam"]["nodes"]),"all_radius_readbacks_match_requested":radii.size==int(candidate["beam"]["nodes"]) and np.allclose(radii,r,rtol=0,atol=tol),"actual_effective_distances":actual,"frozen_point_effective_contact_distance_m":float(base["simulation"]["contact_distance_m"]),"frozen_point_effective_alarm_distance_m":float(base["simulation"]["alarm_distance_m"]),"reconstruction_tolerance_m":tol,"detection_value_reconstruction_samples":count,"detection_value_reconstruction_max_abs_error_m":maximum};out["pass"]=s["beam_collision_model"]=="SphereCollisionModel" and float(s["beam_default_radius_m"])==r and out["all_radius_readbacks_match_requested"] and abs(float(s["beam_model_contact_distance_m"]))<=tol and abs(float(s["fixture_model_contact_distance_m"]))<=tol and abs(actual["effective_contact_distance_m"]-out["frozen_point_effective_contact_distance_m"])<=tol and abs(actual["effective_alarm_distance_m"]-out["frozen_point_effective_alarm_distance_m"])<=tol and count>0 and maximum<=tol;return out
def choose_verdict(**k):
 for flag,v in [("instrumentation_pass",V_INST),("semantics_pass",V_SEMANTICS),("zero_load_pass",V_ZERO),("barrier_pass",V_CROSS),("edge_pass",V_EDGE),("contact_pass",V_CONTACT),("reaction_pass",V_REACTION),("geometry_pass",V_GEOMETRY)]:
  if not k[flag]:return v
 return V_PASS
def reaction_gate(records,classes,config,*,reaction_floor=0.):
 pairs=[(r,c) for r,c in zip(records,classes) if r["measurement_active"] and c["geometric_contact"]];vals=np.asarray([float(r["reaction_force_proxy"]) for r,_ in pairs],float);lc=np.asarray([bool(c["lcp_rows_present"]) for _,c in pairs],bool);floor=float(reaction_floor);on=lambda pred:next((float(r["step_end_time_s"]) for r,c in zip(records,classes) if pred(r,c)),None);gt=on(lambda r,c:c["geometric_contact"]);rt=on(lambda r,c:float(r["reaction_force_proxy"])>floor);lag=None if gt is None or rt is None else rt-gt;tol=float(config["integrity"]["time_tolerance_s"]);maxlag=float(config["gates"]["maximum_native_lcp_onset_lag_steps"])*float(config["simulation"]["dt_s"])
 out={"geometric_measurement_frames":len(pairs),"lcp_fraction":float(lc.mean()) if lc.size else 0.,"positive_reaction_fraction":float((vals>floor).mean()) if vals.size else 0.,"reaction_floor_c0_p99":floor,"reaction_p10":float(np.percentile(vals,10)) if vals.size else None,"reaction_p50":float(np.percentile(vals,50)) if vals.size else None,"reaction_p90":float(np.percentile(vals,90)) if vals.size else None,"reaction_max":float(vals.max()) if vals.size else None,"geometric_onset_s":gt,"reaction_onset_s":rt,"signed_reaction_minus_geometric_onset_s":lag,"allowed_positive_onset_lag_s":maxlag,"time_tolerance_s":tol,"pre_geometric_reaction_frames":sum(float(r["reaction_force_proxy"])>floor for r,c in zip(records,classes) if not c["geometric_contact"])}
 out["causal_order_pass"]=lag is not None and lag>=-tol;out["onset_lag_pass"]=lag is not None and lag<=maxlag+tol;out["pass"]=bool(vals.size) and out["lcp_fraction"]>=float(config["gates"]["minimum_contact_lcp_fraction"]) and out["positive_reaction_fraction"]>=float(config["gates"]["minimum_contact_positive_reaction_fraction"]) and out["reaction_p10"]>floor and out["causal_order_pass"] and out["onset_lag_pass"];return out
def geometry_gate(records,classes,config):
 selected=[];unique=[];spans=[]
 for r,c in zip(records,classes):
  if r["measurement_active"] and c["geometric_contact"]:
   q=[x for x in r["native_contacts"] if float(x["detection_value_m"])<=0];selected+=q;unique.append(len({int(x["beam_element_id"]) for x in q}));xs=[float(x["beam_contact_point_m"][0]) for x in q];spans.append(float(np.ptp(xs)) if xs else 0.)
 if not selected:return {"evaluated":True,"geometric_contact_samples":0,"pass":False}
 fixture=np.asarray([x["fixture_contact_point_m"] for x in selected],float); normals=np.asarray([x["beam_outward_normal"] for x in selected],float);g=config["gates"];out={"evaluated":True,"geometric_contact_samples":len(selected),"fixture_plane_error_max_m":float(np.max(abs(fixture[:,1]-float(config["contact_wall"]["plane_y_m"])))),"normal_alignment_p10":float(np.percentile(abs(normals[:,1]),10)),"unique_beam_primitives_p95":float(np.percentile(unique,95)),"contact_x_span_p95_m":float(np.percentile(spans,95))};out["pass"]=out["fixture_plane_error_max_m"]<=float(g["maximum_fixture_plane_error_m"]) and out["normal_alignment_p10"]>=float(g["minimum_normal_alignment_p10"]) and out["unique_beam_primitives_p95"]<=float(g["maximum_unique_beam_primitives_p95"]) and out["contact_x_span_p95_m"]<=float(g["maximum_contact_x_span_p95_m"]);return out
def relation_table(records,classes):
 out=[]
 for r,c in zip(records,classes):
  out.append({"step":int(r["step"]),"time_s":float(r["step_end_time_s"]),"measurement_active":bool(r["measurement_active"]),"zero_load_phase":bool(r["zero_load_phase"]),"native_detection":bool(c["native_detection"]),"geometric_contact":bool(c["geometric_contact"]),"proximity_only":bool(c["proximity_only"]),"reaction_active":bool(c["reaction_active"]),"load_bearing_contact":bool(c["load_bearing_contact"])})
 return out
