"""Offline-only Stage-C V2.2-L temporal-precedence audit."""
from __future__ import annotations
import json, subprocess, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]; SPIKE=ROOT/"simulator-spikes"/"sofa-beam-spike";sys.path.insert(0,str(SPIKE/"src"))
from stage_c_contact_semantics import classify_record
from stage_c_loss_temporal_order import VERDICT_AMBIGUOUS,VERDICT_CROSSING_FIRST,VERDICT_EXIT_FIRST,audit_temporal_order
BASE_HEAD="3d844aa0cdde64c7a4427bcbc4280f0f84dac21d";BRANCH="phase0s-sofa-beamadapter"
CONFIG=SPIKE/"configs"/"stage_c_stable_contact_v2_2_fixture_extent.json";SEMANTICS=SPIKE/"src"/"stage_c_contact_semantics.py";MORPHOLOGY=SPIKE/"src"/"stage_c_contact_loss_morphology.py"; TRACE=SPIKE/"reports"/"phase0s_sofa"/"data"/"stage_c_v2_2_fixture_extent_trace.json";V22=SPIKE/"reports"/"phase0s_sofa"/"stage_c_fixture_extent_v2_2_metrics.json";OUT=SPIKE/"reports"/"phase0s_sofa"/"stage_c_loss_temporal_order_v2_2l_metrics.json";REPORT=SPIKE/"reports"/"phase0s_sofa"/"STAGE_C_LOSS_TEMPORAL_ORDER_V2_2L.md"
EXPECTED={CONFIG:"0e7f1bc9a4b82defc602701bdeb14022acc4e543",SEMANTICS:"a130d83e11ba4702c44b94344f766f44df6abbc7",MORPHOLOGY:"fc45ae04dbc4e27072cf5301b848ae661014e4ee",TRACE:"ef9289179126509d4312884ab7540eded1b8890a",V22:"7c63358435c7108226b5f2eca8a585775cc19388"}
def git(*args):return subprocess.check_output(["git",*args],cwd=ROOT,text=True).strip()
def gate():
 actual={str(p.relative_to(ROOT)):git("hash-object",str(p)) for p in EXPECTED};expected={str(p.relative_to(ROOT)):b for p,b in EXPECTED.items()};head=git("rev-parse","HEAD");branch=git("branch","--show-current");return {"head":head,"required_head":BASE_HEAD,"branch":branch,"required_branch":BRANCH,"blob_hashes":actual,"expected_blob_hashes":expected,"pass":head==BASE_HEAD and branch==BRANCH and actual==expected}
def narrative(v,a):
 if v==VERDICT_CROSSING_FIRST:return {"fact":f"The first frozen-consistent completed in-footprint wall-plane crossing occurs at {a['first_crossing_time_s']:.12g} s, before the earliest permanent mobile-node fixture exit at {a['first_permanent_node_exit_time_s']:.12g} s.","inference":"Cross-through is temporally established before fixture escape begins at the per-node level in the immutable V2.2 trajectory.","unknown":"Temporal precedence does not prove that crossing causes fixture escape.","next_action":"Review this evidence, then verify official SOFA v26.06 radius/contactDistance composition before authorizing exactly one collision-representation correction."}
 if v==VERDICT_EXIT_FIRST:return {"fact":f"The earliest permanent mobile-node fixture exit occurs at {a['first_permanent_node_exit_time_s']:.12g} s, before the first frozen-consistent completed crossing at {a['first_crossing_time_s']:.12g} s.","inference":"Fixture-boundary escape begins temporally before cross-through; crossing cannot be treated as uniquely upstream in this trace.","unknown":"Temporal precedence does not prove that the implicated boundary causes later crossing.","next_action":"Review the earliest permanent-exit boundary and authorize at most one boundary-specific correction."}
 return {"fact":"The V2.2-L audit did not establish a valid first-crossing versus first-permanent-node-exit temporal ordering.","inference":"No new physical correction is authorized from this result.","unknown":"The upstream Stage-C loss ordering remains unresolved.","next_action":"Inspect crossing consistency and the per-node crossing/exit table; do not change physics."}
def table(rows):return "\n".join(["| node | crossing time (s) | permanent exit time (s) | exit-crossing (s) | boundary |","|---:|---:|---:|---:|:---|"]+[f"| {r['node_id']} | {r['crossing_time_s'] if r['crossing_time_s'] is not None else '—'} | {r['permanent_exit_time_s'] if r['permanent_exit_time_s'] is not None else '—'} | {r['exit_minus_crossing_s'] if r['exit_minus_crossing_s'] is not None else '—'} | {', '.join(r['exit_boundary'])} |" for r in rows])
def write(m):OUT.write_text(json.dumps(m,indent=2)+"\n",encoding="utf-8");a=m.get("temporal_order",{});REPORT.write_text(f"# Phase 0S-SOFA Stage C V2.2-L Loss Temporal-Precedence Audit\n\n## Verdict\n\n`{m['verdict']}`\n\n## Scope\n\nOffline-only analysis of the immutable V2.2 trace. No SOFA, Docker, GPU, trace regeneration, physics change, cleanup, Oracle work, Stage D/E/F, capability, passage, matched-state audit, or training occurred. Temporal precedence is not causal proof.\n\n## Per-node crossing → permanent-exit table\n\n{table(a.get('per_node_crossing_exit_table',[]))}\n\n## Decision metrics\n\n```json\n{json.dumps(m,indent=2)}\n```\n\n## Fact\n\n{m['fact']}\n\n## Inference\n\n{m['inference']}\n\n## Unknown\n\n{m['unknown']}\n\n## Next action\n\n{m['next_action']}\n",encoding="utf-8")
def main():
 source=gate();m={"stage":"Phase 0S-SOFA Stage C V2.2-L","analysis_type":"temporal_precedence","formal_comparison":"first_crossing_vs_earliest_permanent_mobile_node_fixture_exit","execution":"offline-only","sofa_executed":False,"docker_executed":False,"gpu_used":False,"trace_regenerated":False,"physics_changed":False,"cleanup_executed":False,"stage_d_e_f_executed":False,"oracle_fitted":False,"oracle_frozen":False,"capability_executed":False,"passage_executed":False,"matched_state_audit_executed":False,"training_executed":False,"input_gate":source}
 if not source["pass"]:m.update(verdict="PHASE0S_SOFA_STAGE_C_V2_2L_INPUT_INVALID",fact="The frozen V2.2 input identity gate failed.",inference="No temporal-order conclusion is permitted.",unknown="The Stage-C upstream loss ordering remains unresolved.",next_action="Restore the exact frozen V2.2 inputs; do not run physics.");write(m);print(m["verdict"]);return 2
 config=json.loads(CONFIG.read_text());payload=json.loads(TRACE.read_text());v22=json.loads(V22.read_text())
 if v22.get("verdict")!="PHASE0S_SOFA_STAGE_C_V2_2_FIXTURE_EXTENT_NOT_CORRECTED" or not v22["mobile_fixture_edge_gate"]["fixture_edge_escape"]:raise RuntimeError("frozen V2.2 state changed")
 frozen=v22["secondary_morphology"]["crossing_events"]
 if len(frozen)!=int(v22["secondary_morphology"]["crossing_event_count"]) or not frozen:raise RuntimeError("frozen V2.2 crossing evidence invalid")
 records=payload["records"];floor=float(v22["historical_c0"]["reaction_p99"]);effective=float(config["simulation"]["contact_distance_m"]);classes=[classify_record(r,effective_contact_distance_m=effective,reaction_floor=floor) for r in records];a=audit_temporal_order(records,classes,config=config,frozen_crossing_events=frozen);m.update(frozen_v2_2_verdict=v22["verdict"],frozen_crossing_event_count=len(frozen),frozen_terminal_mobile_edge_escape=True,effective_contact_distance_m=effective,reaction_floor_c0_p99=floor,temporal_order=a,verdict=a["verdict"]);m.update(narrative(m["verdict"],a));write(m);print(m["verdict"]);return 0
if __name__=="__main__":raise SystemExit(main())
