#!/usr/bin/env python3
"""Offline V2.4 stable-contact loss morphology audit."""
from __future__ import annotations
import json,math,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];SPIKE=ROOT/'simulator-spikes'/'sofa-beam-spike';sys.path.insert(0,str(SPIKE/'src'))
from stage_c_coupled_correction_v2_4 import classify_trace
from stage_c_v2_4_contact_loss_morphology import V_ALARM_EXIT,V_DROPOUT,V_FOOTPRINT,V_MIXED,V_PROXIMITY,audit_stable_contact_loss
SOURCE_EVIDENCE_COMMIT='01ba714f37bb60eb8f457b9666c72265692325cc';EXPECTED_SOURCE_VERDICT='PHASE0S_SOFA_STAGE_C_V2_4_CONTACT_CONSTRUCTION_FAIL';CONFIG=SPIKE/'configs'/'stage_c_coupled_correction_v2_4.json';SOURCE_TRACE=SPIKE/'reports'/'phase0s_sofa'/'data'/'stage_c_v2_4_coupled_correction_trace.json';SOURCE_METRICS=SPIKE/'reports'/'phase0s_sofa'/'stage_c_coupled_correction_v2_4_r1_metrics.json';OUT=SPIKE/'reports'/'phase0s_sofa';OUT_METRICS=OUT/'stage_c_v2_4_contact_loss_morphology_metrics.json';OUT_REPORT=OUT/'STAGE_C_V2_4_CONTACT_LOSS_MORPHOLOGY.md'
def load(p):return json.loads(p.read_text())
def close(a,b,t):return math.isfinite(float(a)) and math.isfinite(float(b)) and math.isfinite(float(t)) and float(t)>=0 and abs(float(a)-float(b))<=float(t)
def signature(s):
 t=float(s['semantics']['sphere_triangle']['reconstruction_tolerance_m']);c=s['contact'];checks={'source_verdict':s['verdict']==EXPECTED_SOURCE_VERDICT,'source_trace_reused':bool(s['source_trace_reused']),'source_trace_record_count':int(s['source_trace_record_count'])==500,'semantics_pass':bool(s['semantics']['pass']),'zero_load_pass':bool(s['zero_load']['pass']),'barrier_pass':bool(s['barrier']['pass']),'crossing_count_zero':int(s['barrier']['crossing_event_count'])==0,'mobile_fixture_edge_pass':bool(s['mobile_fixture_edge']['pass']),'fixture_edge_escape_false':s['mobile_fixture_edge']['fixture_edge_escape'] is False,'contact_failed':c['pass'] is False,'occupancy':close(c['episode']['occupancy'],.4257142857142857,t),'longest_dwell':close(c['episode']['longest_duration_s'],.09400000000000008,t),'reaction_not_evaluated':s['reaction']['evaluated'] is False,'geometry_not_evaluated':s['geometry']['evaluated'] is False};return {'checks':checks,'pass':bool(all(checks.values()))}
def narrative(v):
 x={V_PROXIMITY:('Every internal contact gap preserves mobile native proximity detection while formal geometric contact is absent.','The repeated contact losses are not explained by alarm-envelope exit, native-detection dropout, or temporary footprint loss.','Review frozen coupled-correction and damping semantics, then authorize exactly one bounded contact-stabilization intervention.'),V_ALARM_EXIT:('At least one internal contact gap leaves the frozen effective alarm envelope.','The stable-contact failure includes genuine separation/rebound rather than only formal-contact threshold loss.','Review separation timing and damping/correction dynamics before authorizing one bounded rebound-control intervention.'),V_DROPOUT:('At least one internal gap loses mobile native detection while geometry remains within the alarm envelope.','Collision/contact-generation persistence deserves priority over response tuning.','Review frozen narrow-phase/contact-generation path before authorizing another physical run.'),V_FOOTPRINT:('At least one internal gap temporarily loses all mobile nodes from the finite fixture footprint.','Terminal fixture-edge PASS does not describe the full measurement-window support trajectory.','Review temporary footprint-loss trajectory before changing fixture geometry.'),V_MIXED:('Internal stable-contact gaps contain more than one morphology class.','No single contact-loss mechanism is established by the frozen trace.','Review the earliest mechanistically distinct gap before authorizing exactly one bounded intervention.')};a,b,n=x[v];return {'fact':a,'inference':b,'unknown':'Node migration and global LCP/reaction are diagnostic only; no node-specific constraint-row attribution is available.','next_action':n}
def table(gaps):
 return '\n'.join(['| gap | class | start s | end s | native frac | LCP frac | reaction frac | pre nodes | post nodes | overlap |','|---:|---|---:|---:|---:|---:|---:|---|---|---|']+[f"| {i} | {g['gap_class']} | {g['start_time_s']:.6f} | {g['end_time_s']:.6f} | {g['mobile_native_detection_fraction']:.3f} | {g['global_lcp_present_fraction']:.3f} | {g['global_reaction_active_fraction']:.3f} | {g['pre_contact_node_ids']} | {g['post_contact_node_ids']} | {g['overlap_node_ids']} |" for i,g in enumerate(gaps,1)])
def main():
 if OUT_METRICS.exists() or OUT_REPORT.exists():print('V2.4-L evidence already exists; refusing to overwrite.',file=sys.stderr);return 2
 if not all(x.is_file() for x in (CONFIG,SOURCE_TRACE,SOURCE_METRICS)):print('missing frozen input',file=sys.stderr);return 2
 c,s,t=load(CONFIG),load(SOURCE_METRICS),load(SOURCE_TRACE);sig=signature(s)
 if not sig['pass']:print(json.dumps(sig,indent=2),file=sys.stderr);return 2
 if len(t['records'])!=500:print('frozen trace record count is not 500',file=sys.stderr);return 2
 actual=s['semantics']['sphere_triangle']['actual_effective_distances'];contact,alarm=float(actual['effective_contact_distance_m']),float(actual['effective_alarm_distance_m']);floor=float(s['reaction_floor_c0_p99']);classes=classify_trace(t['records'],effective_contact_distance_m=contact,reaction_floor=floor);morph=audit_stable_contact_loss(t['records'],classes,config=c,effective_alarm_distance_m=alarm);tol=float(c['integrity']['time_tolerance_s']);src=s['contact'];rep={'occupancy_matches':close(morph['recomputed_contact_occupancy'],src['episode']['occupancy'],tol),'episode_count_matches':int(morph['recomputed_episode_count'])==int(src['episode']['episodes']),'longest_dwell_matches':close(morph['recomputed_longest_timestamp_span_s'],src['episode']['longest_duration_s'],tol)};rep['pass']=bool(all(rep.values()))
 if not rep['pass']:print(json.dumps(rep,indent=2),file=sys.stderr);return 2
 m={'stage':'Phase 0S-SOFA Stage C V2.4-L','execution':'offline-only stable-contact loss morphology audit','source_evidence_commit':SOURCE_EVIDENCE_COMMIT,'source_verdict':s['verdict'],'source_trace_reused':True,'source_trace_record_count':500,'sofa_executed':False,'docker_executed':False,'gpu_executed':False,'trace_regenerated':False,'physics_changed':False,'thresholds_changed':False,'source_signature':sig,'contact_gate_reproduction':rep,'effective_contact_distance_m':contact,'effective_alarm_distance_m':alarm,'reaction_floor_c0_p99':floor,**morph};m.update(narrative(m['verdict']));OUT_METRICS.write_text(json.dumps(m,indent=2)+'\n');OUT_REPORT.write_text('# Phase 0S-SOFA Stage C V2.4-L Stable-Contact Loss Morphology Audit\n\n## Verdict\n\n`'+m['verdict']+'`\n\n## Execution\n\nOffline-only audit of the frozen V2.4 coupled-correction trace. No SOFA, Docker, GPU, trace regeneration, physics change or threshold change.\n\n## Frozen failed gate\n\n- occupancy: '+str(m['recomputed_contact_occupancy'])+'\n- episodes: '+str(m['recomputed_episode_count'])+'\n- longest timestamp-span dwell: '+str(m['recomputed_longest_timestamp_span_s'])+' s\n- internal gaps: '+str(m['internal_gap_count'])+'\n\n## Gap classes\n\n```json\n'+json.dumps(m['gap_class_counts'],indent=2)+'\n```\n\n## Per-gap summary\n\n'+table(m['internal_gaps'])+'\n\n## Fact\n\n'+m['fact']+'\n\n## Inference\n\n'+m['inference']+'\n\n## Unknown\n\n'+m['unknown']+'\n\n## Next action\n\n'+m['next_action']+'\n');print(m['verdict']);return 0
if __name__=='__main__':raise SystemExit(main())
