#!/usr/bin/env python3
"""Offline V2.4-R1 semantic-baseline repair and scientific re-audit."""
from __future__ import annotations
import json,math,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];SPIKE=ROOT/'simulator-spikes'/'sofa-beam-spike';sys.path.insert(0,str(SPIKE/'src'))
from stage_c_coupled_correction_v2_4 import V_CONTACT,V_CROSS,V_EDGE,V_GEOMETRY,V_PASS,V_REACTION,V_SEMANTICS,V_ZERO,barrier_crossing_gate,classify_trace,contact_gate,geometry_gate,mobile_fixture_edge_gate,reaction_gate,semantics_gate,zero_load_gate
SOURCE_EVIDENCE_COMMIT='4289659b027b929d69282fc47f8ecda4476663ad';EXPECTED_SOURCE_VERDICT='PHASE0S_SOFA_STAGE_C_V2_4_COUPLED_CORRECTION_SEMANTICS_FAIL';V24_CONFIG=SPIKE/'configs'/'stage_c_coupled_correction_v2_4.json';CORRECT_POINT_BASE=SPIKE/'configs'/'stage_c_stable_contact_v2_2_fixture_extent.json';WRONG_SPHERE_BASE=SPIKE/'configs'/'stage_c_collision_radius_v2_3.json';SOURCE_TRACE=SPIKE/'reports'/'phase0s_sofa'/'data'/'stage_c_v2_4_coupled_correction_trace.json';SOURCE_METRICS=SPIKE/'reports'/'phase0s_sofa'/'stage_c_coupled_correction_v2_4_metrics.json';OUT_METRICS=SPIKE/'reports'/'phase0s_sofa'/'stage_c_coupled_correction_v2_4_r1_metrics.json';OUT_REPORT=SPIKE/'reports'/'phase0s_sofa'/'STAGE_C_COUPLED_CORRECTION_V2_4_R1.md'
def load_json(p):return json.loads(p.read_text(encoding='utf-8'))
def close(a,b,atol=1e-12):return math.isfinite(float(a)) and math.isfinite(float(b)) and abs(float(a)-float(b))<=atol
def source_failure_signature(source,point,candidate):
 sphere=source['semantics']['sphere_triangle'];stack=source['semantics']['response_stack'];actual=sphere['actual_effective_distances'];pc=float(point['simulation']['contact_distance_m']);pa=float(point['simulation']['alarm_distance_m']);wc=float(sphere['frozen_point_effective_contact_distance_m']);wa=float(sphere['frozen_point_effective_alarm_distance_m']);gc=float(candidate['simulation']['contact_distance_m']);ga=float(candidate['simulation']['alarm_distance_m']);checks={'source_verdict_is_semantics_fail':source['verdict']==EXPECTED_SOURCE_VERDICT,'formal_c1_completed':int(source['formal_c1_completed'])==1,'source_instrumentation_pass':bool(source['instrumentation']['pass']),'source_response_stack_pass':bool(stack['pass']),'source_sphere_semantics_failed':not bool(sphere['pass']),'reconstruction_samples_positive':int(sphere['detection_value_reconstruction_samples'])>0,'reconstruction_error_zero':close(sphere['detection_value_reconstruction_max_abs_error_m'],0),'actual_contact_matches_correct_point':close(actual['effective_contact_distance_m'],pc),'actual_alarm_matches_correct_point':close(actual['effective_alarm_distance_m'],pa),'wrong_expected_contact_equals_sphere_global':close(wc,gc),'wrong_expected_alarm_equals_sphere_global':close(wa,ga),'correct_point_contact_is_0p002':close(pc,.002),'correct_point_alarm_is_0p010':close(pa,.01),'zero_not_evaluated':source['zero_load']['evaluated'] is False,'barrier_not_evaluated':source['barrier']['evaluated'] is False};return {'checks':checks,'wrong_point_baseline_used_by_source_audit':{'contact_m':wc,'alarm_m':wa},'correct_point_baseline':{'contact_m':pc,'alarm_m':pa},'actual_sphere_effective_envelope':{'contact_m':float(actual['effective_contact_distance_m']),'alarm_m':float(actual['effective_alarm_distance_m'])},'pass':bool(all(checks.values()))}
def effective_contact_from_trace(p):
 s=p['metadata']['collision_snapshot'];v=[float(s[k]) for k in ('intersection_contact_distance_m','beam_default_radius_m','beam_model_contact_distance_m','fixture_model_contact_distance_m')]
 if not all(math.isfinite(x) for x in v):raise RuntimeError('non-finite V2.4 effective-contact term')
 return sum(v)
def corrected_semantics(payload,candidate,point,reaction_floor):
 eff=effective_contact_from_trace(payload);classes=classify_trace(payload['records'],effective_contact_distance_m=eff,reaction_floor=float(reaction_floor));return classes,semantics_gate(payload,classes,candidate,point),eff
def skipped(r):return {'evaluated':False,'reason':r}
def gates(payload,candidate,point,floor):
 classes,sem,eff=corrected_semantics(payload,candidate,point,floor);out={'corrected_effective_contact_distance_m':eff,'semantics':sem}
 if not sem['pass']:out.update(verdict=V_SEMANTICS,zero_load=skipped('corrected semantics failed'),barrier=skipped('corrected semantics failed'),mobile_fixture_edge=skipped('corrected semantics failed'),contact=skipped('corrected semantics failed'),reaction=skipped('corrected semantics failed'),geometry=skipped('corrected semantics failed'));return out
 for key,fn,v,rest in [('zero_load',lambda:zero_load_gate(payload['records'],classes),V_ZERO,['barrier','mobile_fixture_edge','contact','reaction','geometry']),('barrier',lambda:barrier_crossing_gate(payload['records'],classes,candidate),V_CROSS,['mobile_fixture_edge','contact','reaction','geometry']),('mobile_fixture_edge',lambda:mobile_fixture_edge_gate(payload['records'],classes,candidate),V_EDGE,['contact','reaction','geometry']),('contact',lambda:contact_gate(payload['records'],classes,candidate),V_CONTACT,['reaction','geometry']),('reaction',lambda:reaction_gate(payload['records'],classes,candidate,reaction_floor=float(floor)),V_REACTION,['geometry'])]:
  x=fn();out[key]=x
  if not x['pass']:out.update(verdict=v,**{z:skipped(key+' gate failed') for z in rest});return out
 geo=geometry_gate(payload['records'],classes,candidate);out.update(geometry=geo,verdict=V_PASS if geo['pass'] else V_GEOMETRY);return out
def narrative(v):
 msgs={V_SEMANTICS:('The corrected V2.2 Point baseline still does not qualify the frozen V2.4 semantics.','The wrong-baseline false negative was not the only semantics blocker.','Review only the corrected semantics mismatch; do not run another C1 automatically.'),V_ZERO:('Corrected semantics pass, but the frozen V2.4 trace fails the zero-load gate.','The coupled-correction formulation perturbs the contact-free baseline before formal loading.','Review the zero-load behavior on the same frozen trace.'),V_CROSS:('After repairing the semantic baseline, positive-to-negative wall crossing persists in the frozen V2.4 trace.','Replacing the prescribed uncoupled compliance formulation with LinearSolverConstraintCorrection was insufficient to eliminate cross-through under the frozen Stage-C setup.','Review the deferred sidedness/topology falsification experiment before authorizing any new physical run.'),V_EDGE:('The coupled correction eliminates wall-plane crossing, but mobile fixture escape persists.','The correction formulation repairs cross-through but does not complete Stage C.','Review the post-contact trajectory before changing fixture support.'),V_CONTACT:('Barrier and fixture-edge gates pass, but the frozen V2.4 trace fails stable-contact occupancy/dwell.','Coupled correction prevents cross-through but does not establish required sustained contact.','Review contact-loss morphology with V2.4 physics frozen.'),V_REACTION:('Stable geometric contact passes, but reaction qualification fails on the frozen V2.4 trace.','Barrier geometry/contact persistence are sufficient, but the response signal is not qualified.','Review reaction/constraint coupling with V2.4 physics frozen.'),V_GEOMETRY:('Barrier, stable contact and reaction pass, but local-contact geometry fails.','Stage C remains blocked by contact-distribution geometry.','Review contact distribution without relaxing frozen gates.'),V_PASS:('The same completed V2.4 coupled-correction C1 passes corrected Sphere semantics and every frozen Stage-C gate.','Replacing the prescribed uncoupled compliance formulation with the linear-solver-derived correction formulation was sufficient to eliminate cross-through and qualify stable normal contact under the frozen Stage-C setup.','Authorize Stage D breakaway characterization with the V2.4 correction stack frozen.')};a,b,n=msgs[v];return {'fact':a,'inference':b,'unknown':'The experiment does not isolate off-diagonal coupling from other formulation differences; node-specific constraint-row force attribution remains unavailable.','next_action':n}
def write(m):
 OUT_METRICS.write_text(json.dumps(m,indent=2)+'\n');g={k:m.get(k) for k in ('semantics','zero_load','barrier','mobile_fixture_edge','contact','reaction','geometry')};OUT_REPORT.write_text('# Phase 0S-SOFA Stage C V2.4-R1 Semantic-Baseline Repair + Offline Re-Audit\n\n## Verdict\n\n`'+m['verdict']+'`\n\n## Execution\n\nOffline-only re-audit of the already committed V2.4 physical trace. No SOFA, Docker, GPU, trace regeneration or physics change.\n\n## Source failure signature\n\n```json\n'+json.dumps(m['source_failure_signature'],indent=2)+'\n```\n\n## Corrected gates\n\n```json\n'+json.dumps(g,indent=2)+'\n```\n\n## Fact\n\n'+m['fact']+'\n\n## Inference\n\n'+m['inference']+'\n\n## Unknown\n\n'+m['unknown']+'\n\n## Next action\n\n'+m['next_action']+'\n')
def main():
 if OUT_METRICS.exists() or OUT_REPORT.exists():print('V2.4-R1 evidence already exists; refusing to overwrite.',file=sys.stderr);return 2
 if not all(p.is_file() for p in (V24_CONFIG,CORRECT_POINT_BASE,WRONG_SPHERE_BASE,SOURCE_TRACE,SOURCE_METRICS)):print('missing required frozen input',file=sys.stderr);return 2
 source=load_json(SOURCE_METRICS);candidate=load_json(V24_CONFIG);point=load_json(CORRECT_POINT_BASE);payload=load_json(SOURCE_TRACE);sig=source_failure_signature(source,point,candidate)
 if not sig['pass']:print(json.dumps(sig,indent=2),file=sys.stderr);return 2
 if payload['metadata'].get('mode')!='coupled_constraint_correction_c1' or len(payload['records'])!=int(source['instrumentation']['records']):print('source trace mismatch',file=sys.stderr);return 2
 floor=float(source['reaction_floor_c0_p99']);scientific=gates(payload,candidate,point,floor);m={'stage':'Phase 0S-SOFA Stage C V2.4-R1','execution':'offline-only semantic-baseline repair and re-audit','source_evidence_commit':SOURCE_EVIDENCE_COMMIT,'source_verdict':source['verdict'],'source_formal_c1_requested':int(source['formal_c1_requested']),'source_formal_c1_completed':int(source['formal_c1_completed']),'source_trace_reused':True,'source_trace_record_count':len(payload['records']),'sofa_executed':False,'docker_executed':False,'gpu_executed':False,'trace_regenerated':False,'physics_changed':False,'thresholds_changed':False,'source_instrumentation':source['instrumentation'],'source_response_stack':source['semantics']['response_stack'],'source_failure_signature':sig,'reaction_floor_c0_p99':floor,**scientific};m.update(narrative(m['verdict']));write(m);print(m['verdict']);return 0
if __name__=='__main__':raise SystemExit(main())
